# hugo server --minify

baseURL = "/"
languageCode = "en-us"
title = "Principia"
theme = "hugo-book"

# Book configuration
disablePathToLower = true
#enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/ailidani"
  weight = 10

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = '/'
  BookRepo = 'https://github.com/ailidani/principia'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
