# hugo server --minify --disableFastRender

baseURL = "/"
languageCode = "en-us"
title = "Principia"
theme = "hugo-book"
googleAnalytics = "G-3P4X93VJZC"

# configuration
disablePathToLower = true
enableGitInfo = true
enableEmoji = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/ailidani"
  weight = 10

[[menu.after]]
  name = "Google Scholar"
  url = "https://scholar.google.com/citations?user=D6PWsuwAAAAJ&hl=en"
  weight = 20

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = '/'
  BookRepo = 'https://github.com/ailidani/principia'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true
  BookTranslatedOnly = false
